blog/urls.py
from django.urls import path, include
from . import views
from . import api_views

api_urls = [
	path('article_list/', api_views.ArticleListView.as_view(), name='article_list'),
	path('article_detail/<int:article_id>', api_views.ArticleDetailView.as_view(), name='article_detail'),
]



app_name = 'blog'
urlpatterns = [
    path('', views.home, name='home'),
    path('detail/<pk>/', views.article_detail, name='detail'),
    path('add_reply/<int:article_id>/<int:comment_id>/', views.add_reply, name='add_reply'),


    # likes
    path('like/article/<int:article_id>/',
         views.BlogLike.as_view(), name='article_like'),

    path('api/', include(api_urls))

]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
import debug_toolbar
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls', namespace='blog')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('__debug__/', include(debug_toolbar.urls)),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns

    # serve static and media files from development server
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.urls import reverse
from django.utils.text import slugify

from blog.utils import slugify_instance_title
from sorl.thumbnail import ImageField
User = get_user_model()


class Category(models.Model):
    title = models.TextField(max_length=100)
    slug = models.SlugField()

    def __str__(self):
        return self.title


class Article(models.Model):
    STATUS = [
        ('D', 'Draft'),
        ('P', 'Publish'),
    ]
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True, blank=True)
    title = models.CharField(max_length=250)
    slug = models.SlugField(unique=True, null=True, blank=True)
    content = models.TextField()
    image = ImageField(upload_to='blog-images/') # using sorl-thumbnail
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=250, choices=STATUS)
    likes = models.ManyToManyField(
        User, related_name='blog_like', null=True, blank=True)
    # def get_absolute_url(self):
    #     return reverse("blog:detail", kwargs={"id": self.id})

    def __str__(self):
        return self.title

    def likes_count(self=None, d=None):
        return self.likes.count()

    def save(self, *args, **kwargs):
        if self.slug is None:
            slugify_instance_title(self, save=False)
        super(Article, self).save(*args, **kwargs)


class Comment(models.Model):
	user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='ucomment')
	article = models.ForeignKey(Article, on_delete=models.CASCADE, related_name='acomment')
	reply = models.ForeignKey('self', on_delete=models.CASCADE, null=True, blank=True, related_name='rcomment')
	is_reply = models.BooleanField(default=False)
	body = models.TextField(max_length=400)
	created = models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return f'{self.user} - {self.body[:30]}'

	class Meta:
		ordering = ('-created',)

blog/forms.py
from django import forms
from .models import Comment


class AddCommentForm(forms.ModelForm):
	class Meta:
		model = Comment
		fields = ('body',)
		widgets = {
			'body': forms.Textarea(attrs={'class':'form-control'})
		}
		error_messages = {
			'body':{
				'required': 'This fields is required',
			}
		}
		help_texts = {
			'body':'max 400 char'
		}

class AddReplyForm(forms.ModelForm):
	class Meta:
		model = Comment
		fields = ('body',)

blog/views.py
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.views.generic import ListView, DetailView, View
from django.contrib.auth import get_user_model
from .models import Article, Comment
from .tasks import task_like_article, task_send_mail
from .mixins import CacheMixin
from .forms import AddCommentForm, AddReplyForm
from django.conf import settings
from django.core.cache.backends.base import DEFAULT_TIMEOUT
from django.shortcuts import render
from django.views.decorators.cache import cache_page
from django.core.cache import cache
from django.contrib import messages
from django.contrib.auth.decorators import login_required

User = get_user_model()

CACHE_TTL = getattr(settings, 'CACHE_TTL', DEFAULT_TIMEOUT)

def home(request):
    articles = Article.objects.all()
    if 'articles' in cache:
        data = cache.get('articles')
        return render(request, 'blog/home.html', {
            'object_list': data,
        })
    cache.set('articles', articles,timeout=CACHE_TTL)
    return render(request, 'blog/home.html', {
        'object_list': articles,
    })


# class ArticleDetailView(View):
#     template_name = 'blog/article_detail.html'
#     comment_form_class = CommentForm
#     reply_form_class = ReplyForm

#     def get(self, request, pk):
#         article = get_object_or_404(Article, pk=pk)
#         if 'article' in cache:
#             data = cache.get('article')
#             return render(request, self.template_name, {
#             'obj': data,
#           })
#         cache.set('article', article, timeout=CACHE_TTL)
#         return render(request, self.template_name, {
#             'obj': article,
#         })
#     def post(self, request):


def article_detail(request, pk):
    article = get_object_or_404(Article, pk=pk)
    comments = Comment.objects.filter(article=article, is_reply=False)
    reply_form = AddReplyForm()
    # if request.user.is_authenticated:
    # 	if article.user_can_like(request.user):
    # 		can_like = True
    if request.method == 'POST':
        form = AddCommentForm(request.POST)
        if form.is_valid():
            new_comment = form.save(commit=False)
            new_comment.article = article
            new_comment.user = request.user
            new_comment.save()
            messages.success(request, 'you comment submitted successfully')
    else:
        form = AddCommentForm()
    return render(request, 'blog/article_detail.html', {
        'article':article,
        'comments':comments,
        'form':form,
        'reply':reply_form,
        })

@login_required
def add_reply(request, article_id, comment_id):
    article = get_object_or_404(Article, pk=article_id)
    print(article)
    comment = get_object_or_404(Comment, pk=comment_id)
    if request.method == 'POST':
        form = AddReplyForm(request.POST)
        if form.is_valid():
            reply = form.save(commit=False)
            reply.user = request.user
            reply.article = article
            reply.reply = comment
            reply.is_reply = True
            reply.save()
            task_send_mail.delay(comment_id=comment.pk, user_id=comment.user.pk, user_replied_id=reply.user.pk)
            messages.success(request, 'your reply submitted successfully', 'success')
    return redirect('blog:detail', article.pk)




class BlogLike(View):

    def get(self, request, article_id):
        # If i pass the request into task, then i will have too many bugs
        user = User.objects.get(id=request.user.id)
        user_id = user.id
        task_like_article.delay(user_id=user_id, article_id=article_id)

        return redirect('blog:detail', article_id)

blog/templates/blog/article_detail.html
{% extends 'base.html' %}
{% load thumbnail %}

{% block title %} - article {{obj.id}} {% endblock title %}


{% block content %}

{{obj.title}}{{obj.content}}

{% thumbnail obj.image "100x100" crop="center" as im %}
<img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}">

{% endthumbnail %}

    {% with total=comments.count %}
    <p>This article has {{ total }} comment{{ total|pluralize }}</p>
    {% endwith %}


    {% if request.user.is_authenticated %}
    <a href="{% url 'blog:article_like' article.id %}"
        class="btn btn-primary {% if can_like %}disabled {% endif %} col-md-2">Like {{ article.likes_count }}</a>
    {% endif %}

        {% if request.user.is_authenticated %}
        <form action="" method="post" novalidate class="col-md-6">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Send" class="btn btn-primary">
        </form>
        {% else %}
        <p>only logged in users can send comments</p>
        {% endif %}<br /><br /><br />


    {% for comment in comments %}
    <div class="card bg-dark text-white">
        <p class="card-header">{{ comment.user }} <a href="">reply</a></p>
        <p class="card-body">{{ comment.body }}</p>
        {% if request.user.is_authenticated %}
        <div class="card-body">
            <form action="{% url 'blog:add_reply' article.id comment.id %}" method="post">
                {% csrf_token %}
                {{ reply }}
                <input type="submit" value="Send">
            </form>
        </div>
        {% else %}
        <p>you have to login to send reply</p>
        {% endif %}
        {% for reply in comment.rcomment.all %}
        <p class="bg-primary text-white p-3 m-5">{{ reply.user }} <br /> {{ reply.body }}</p>
        {% endfor %}
    </div><br />
    {% empty %}
            <p>There is no comment</p>
    {% endfor %}
{% endblock content %}

blog/templates/blog/home.html
{% extends 'base.html' %}


{% block content %}

<h1>Home page</h1>
{% for article in object_list %}
    <p><a href="{% url 'blog:detail' article.id %}">{{ article.title }}</a></p>
{% endfor %}
{% endblock content %}